# Name of the executable
NAME = minishell

# Compilation flags
CFLAGS = -Wall -Wextra -Werror
INCLUDES = -I ./includes/ -I $(LIBFT_PATH)/ -I $(FTPRINTF_PATH)/

# Libft
LIBFT_PATH	=	./libs/libft
LIBFT		=	$(LIBFT_PATH)/libft.a

# Libftprintf
FTPRINTF_PATH	= ./libs/ft_printf
FTPRINTF		=	$(FTPRINTF_PATH)/libftprintf.a

# push_swap
SRC = 	./src/main.c
#		./src/lexer/.c \
#		./src/parser/.c \
#		./src/executor/.c \
#		./src/utils/.c \



# Objects
OBJ_PATH = ./build/
OBJ = $(addprefix $(OBJ_PATH), $(notdir $(SRC:.c=.o)))
# OBJ_PATH_BONUS = ./build_bonus/
# OBJ_BONUS = $(addprefix $(OBJ_PATH_BONUS), $(notdir $(SRC_BONUS:.c=.o)))

# Color codes of output on terminal
GREEN = \e[1;32m
WHITE = \033[1;37m
CYAN= \033[0;36m
END = \033[0m

# Default target to compile the mandatory part
all: $(NAME)

# Target to build the mandatory part
# $(NAME): $(LIBFT) $(OBJ)
# 	@cp $(LIBFT) $(NAME)
# 	$(CC) $(OBJ) $(LIBFT) -L$(PATH_LIBFT) -o $(NAME)
	@echo "$(GREEN)--------------------------------------------------$(END)"
	@echo "$(GREEN)The [$(CYAN)PUSH_SWAP$(GREEN)] has been compiled! 🤠$(END)"
	@echo "$(GREEN)--------------------------------------------------$(END)"

# Builds dependencies
$(LIBFT):
	@make -C $(LIBFT_PATH)
$(FTPRINTF):
	@make -C $(FTPRINTF_PATH)

# Builds mandatory object files
$(OBJ_PATH)%.o: src/%.c
	@mkdir -p $(OBJ_PATH)
	$(CC) -c $(CFLAGS) $< -o $@ $(INCLUDES)

# Cleans object files and dependencies
clean:
	@rm -f $(OBJ)
	@rm -rf $(OBJ_PATH)
	@make -C $(LIBFT_PATH) clean
	@make -C $(FTPRINTF_PATH) clean
	@echo "$(WHITE)-----------------------------------$(END)"
	@echo "$(WHITE)    Object files were cleaned!$(END)"
	@echo "$(WHITE)-----------------------------------$(END)"

# Cleans the executable file and pre-compiled header
fclean: clean
	@echo "$(WHITE)-----------------------------------$(END)"
	@echo "$(WHITE)        Cleaning all... 🧹$(END)"
	@echo "$(WHITE)-----------------------------------$(END)"
	@rm -f $(NAME)
	@rm -f $(HD)*.gch
	@make -C $(LIBFT_PATH) fclean
	@make -C $(FTPRINTF_PATH) fclean
	@echo "$(WHITE)-----------------------------------$(END)"
	@echo "$(WHITE)    ✨ Cleaning complete! ✨$(END)"
	@echo "$(WHITE)-----------------------------------$(END)"

# Cleans everything generated by the Makefile and rebuild it all
re: fclean all

# Phony targets
.PHONY: all bonus clean fclean re
